title: "Jorge Martín Lasaosa"
description: "Blog personal en el que hablar de mis inquietudes y proyectos personales"
url: "https://jomartla.github.io"  # cámbialo cuando conectes dominio

# Use remote theme (GitHub Pages compatible)
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

# Dark mode configuration
# The theme supports built-in dark mode, but we're implementing custom toggle
# Available skins: "default", "dark", "neon", "plum", "sunrise"

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

collections:
  pages:
    output: true
    permalink: /:title/

# Social media links
author:
  name: "Jorge Martín Lasaosa"
  avatar: "/assets/images/bio-photo.jpg"  # Optional: add your photo
  bio: "Científico de datos y desarrollador apasionado por la IA"
  location: "España"
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/jorgemartinlasaosa/"

# Footer configuration
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/jorgemartinlasaosa/"

# Opcional, enlaces del nav (si quieres menú superior)
# nav:
#   - title: "Inicio"
#     url: /
#   - title: "Sobre mí"
#     url: /about/
